Transform: 'AWS::Serverless-2016-10-31'

Resources:
  ContestSubmissionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: download.handler
      Runtime: python3.6
      CodeUri: ./contest_submissions
      MemorySize: 256
      Timeout: 30
      Policies:
        - AmazonKinesisFirehoseFullAccess
        - AWSLambdaInvocation-DynamoDB

  ContestSubmissionsFunctionTrigger:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !GetAtt ContestSubmissionsQueue.StreamArn
      FunctionName: !GetAtt ContestSubmissionsFunction.Arn
      StartingPosition: LATEST
      BatchSize: 1

  ContestSubmissionsFirehose:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamName: codeforces-analysis-contest-submissions
      DeliveryStreamType: DirectPut
      S3DestinationConfiguration:
        BucketARN: arn:aws:s3:::codeforces-analysis
        Prefix: data/contest-submissions/
        CompressionFormat: GZIP
        BufferingHints:
          IntervalInSeconds: 300
          SizeInMBs: 128
        RoleARN: !GetAtt FirehoseRole.Arn

  FirehoseRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  ContestSubmissionsQueue:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: contest_id
          AttributeType: N
      KeySchema:
        - AttributeName: contest_id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      StreamSpecification:
        StreamViewType: KEYS_ONLY
